In [1]:
import nflreadpy as nfl
import polars as pl

In [3]:
schedules = nfl.load_schedules(
    seasons=range(2015, 2026)
)

games = schedules.filter(
    pl.col("game_type") == "REG"
)

games.head()

shape: (5, 46)
┌─────────────┬────────┬───────────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ game_id     ┆ season ┆ game_type ┆ week ┆ … ┆ home_coach  ┆ referee    ┆ stadium_id ┆ stadium    │
│ ---         ┆ ---    ┆ ---       ┆ ---  ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│ str         ┆ i32    ┆ str       ┆ i32  ┆   ┆ str         ┆ str        ┆ str        ┆ str        │
╞═════════════╪════════╪═══════════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2015_01_PIT ┆ 2015   ┆ REG       ┆ 1    ┆ … ┆ Bill        ┆ Carl       ┆ BOS00      ┆ Gillette   │
│ _NE         ┆        ┆           ┆      ┆   ┆ Belichick   ┆ Cheffers   ┆            ┆ Stadium    │
│ 2015_01_IND ┆ 2015   ┆ REG       ┆ 1    ┆ … ┆ Rex Ryan    ┆ John Parry ┆ BUF00      ┆ Ralph      │
│ _BUF        ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Wilson     │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Stadium    │
│ 2015_01_GB_ ┆ 2015   ┆ REG       ┆ 1    ┆ … ┆ John Fox    ┆ Craig      ┆ CHI98      ┆ Soldier    │
│ CHI         ┆        ┆           ┆      ┆   ┆             ┆ Wrolstad   ┆            ┆ Field      │
│ 2015_01_KC_ ┆ 2015   ┆ REG       ┆ 1    ┆ … ┆ Bill        ┆ Peter      ┆ HOU00      ┆ NRG        │
│ HOU         ┆        ┆           ┆      ┆   ┆ O'Brien     ┆ Morelli    ┆            ┆ Stadium    │
│ 2015_01_CAR ┆ 2015   ┆ REG       ┆ 1    ┆ … ┆ Gus Bradley ┆ Ron        ┆ JAX00      ┆ EverBank   │
│ _JAX        ┆        ┆           ┆      ┆   ┆             ┆ Torbert    ┆            ┆ Field      │
└─────────────┴────────┴───────────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [5]:
games.columns

['game_id',
 'season',
 'game_type',
 'week',
 'gameday',
 'weekday',
 'gametime',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'location',
 'result',
 'total',
 'overtime',
 'old_game_id',
 'gsis',
 'nfl_detail_id',
 'pfr',
 'pff',
 'espn',
 'ftn',
 'away_rest',
 'home_rest',
 'away_moneyline',
 'home_moneyline',
 'spread_line',
 'away_spread_odds',
 'home_spread_odds',
 'total_line',
 'under_odds',
 'over_odds',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'away_qb_id',
 'home_qb_id',
 'away_qb_name',
 'home_qb_name',
 'away_coach',
 'home_coach',
 'referee',
 'stadium_id',
 'stadium']

In [6]:
games.schema

Schema([('game_id', String),
        ('season', Int32),
        ('game_type', String),
        ('week', Int32),
        ('gameday', String),
        ('weekday', String),
        ('gametime', String),
        ('away_team', String),
        ('away_score', Int32),
        ('home_team', String),
        ('home_score', Int32),
        ('location', String),
        ('result', Int32),
        ('total', Int32),
        ('overtime', Int32),
        ('old_game_id', String),
        ('gsis', Int32),
        ('nfl_detail_id', String),
        ('pfr', String),
        ('pff', Int32),
        ('espn', String),
        ('ftn', Int32),
        ('away_rest', Int32),
        ('home_rest', Int32),
        ('away_moneyline', Int32),
        ('home_moneyline', Int32),
        ('spread_line', Float64),
        ('away_spread_odds', Int32),
        ('home_spread_odds', Int32),
        ('total_line', Float64),
        ('under_odds', Int32),
        ('over_odds', Int32),
        ('div_game', Int32),
        ('roof', String),
        ('surface', String),
        ('temp', Int32),
        ('wind', Int32),
        ('away_qb_id', String),
        ('home_qb_id', String),
        ('away_qb_name', String),
        ('home_qb_name', String),
        ('away_coach', String),
        ('home_coach', String),
        ('referee', String),
        ('stadium_id', String),
        ('stadium', String)])

In [8]:
home_games = games.select([
    "game_id",
    "season",
    "week",
    "home_team",
    "away_team",
    pl.col("home_team").alias("team"),
    pl.col("home_score").alias("points_for"),
    pl.col("away_score").alias("points_against"),
    (pl.col("result") > 0).cast(pl.Int8).alias("win"),
])

home_games.head()

shape: (5, 9)
┌─────────────────┬────────┬──────┬───────────┬───┬──────┬────────────┬────────────────┬─────┐
│ game_id         ┆ season ┆ week ┆ home_team ┆ … ┆ team ┆ points_for ┆ points_against ┆ win │
│ ---             ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---        ┆ ---            ┆ --- │
│ str             ┆ i32    ┆ i32  ┆ str       ┆   ┆ str  ┆ i32        ┆ i32            ┆ i8  │
╞═════════════════╪════════╪══════╪═══════════╪═══╪══════╪════════════╪════════════════╪═════╡
│ 2015_01_PIT_NE  ┆ 2015   ┆ 1    ┆ NE        ┆ … ┆ NE   ┆ 28         ┆ 21             ┆ 1   │
│ 2015_01_IND_BUF ┆ 2015   ┆ 1    ┆ BUF       ┆ … ┆ BUF  ┆ 27         ┆ 14             ┆ 1   │
│ 2015_01_GB_CHI  ┆ 2015   ┆ 1    ┆ CHI       ┆ … ┆ CHI  ┆ 23         ┆ 31             ┆ 0   │
│ 2015_01_KC_HOU  ┆ 2015   ┆ 1    ┆ HOU       ┆ … ┆ HOU  ┆ 20         ┆ 27             ┆ 0   │
│ 2015_01_CAR_JAX ┆ 2015   ┆ 1    ┆ JAX       ┆ … ┆ JAX  ┆ 9          ┆ 20             ┆ 0   │
└─────────────────┴────────┴──────┴───────────┴───┴──────┴────────────┴────────────────┴─────┘

In [9]:
away_games = games.select([
    "game_id",
    "season",
    "week",
    "home_team",
    "away_team",
    pl.col("away_team").alias("team"),
    pl.col("away_score").alias("points_for"),
    pl.col("home_score").alias("points_against"),
    (pl.col("result") < 0).cast(pl.Int8).alias("win"),
])
away_games.head()

shape: (5, 9)
┌─────────────────┬────────┬──────┬───────────┬───┬──────┬────────────┬────────────────┬─────┐
│ game_id         ┆ season ┆ week ┆ home_team ┆ … ┆ team ┆ points_for ┆ points_against ┆ win │
│ ---             ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---        ┆ ---            ┆ --- │
│ str             ┆ i32    ┆ i32  ┆ str       ┆   ┆ str  ┆ i32        ┆ i32            ┆ i8  │
╞═════════════════╪════════╪══════╪═══════════╪═══╪══════╪════════════╪════════════════╪═════╡
│ 2015_01_PIT_NE  ┆ 2015   ┆ 1    ┆ NE        ┆ … ┆ PIT  ┆ 21         ┆ 28             ┆ 0   │
│ 2015_01_IND_BUF ┆ 2015   ┆ 1    ┆ BUF       ┆ … ┆ IND  ┆ 14         ┆ 27             ┆ 0   │
│ 2015_01_GB_CHI  ┆ 2015   ┆ 1    ┆ CHI       ┆ … ┆ GB   ┆ 31         ┆ 23             ┆ 1   │
│ 2015_01_KC_HOU  ┆ 2015   ┆ 1    ┆ HOU       ┆ … ┆ KC   ┆ 27         ┆ 20             ┆ 1   │
│ 2015_01_CAR_JAX ┆ 2015   ┆ 1    ┆ JAX       ┆ … ┆ CAR  ┆ 20         ┆ 9              ┆ 1   │
└─────────────────┴────────┴──────┴───────────┴───┴──────┴────────────┴────────────────┴─────┘

In [10]:
team_games = pl.concat([
    home_games,
    away_games
]).sort([
    "season",
    "team",
    "week"
])

team_games.head(10)

shape: (10, 9)
┌─────────────────┬────────┬──────┬───────────┬───┬──────┬────────────┬────────────────┬─────┐
│ game_id         ┆ season ┆ week ┆ home_team ┆ … ┆ team ┆ points_for ┆ points_against ┆ win │
│ ---             ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---        ┆ ---            ┆ --- │
│ str             ┆ i32    ┆ i32  ┆ str       ┆   ┆ str  ┆ i32        ┆ i32            ┆ i8  │
╞═════════════════╪════════╪══════╪═══════════╪═══╪══════╪════════════╪════════════════╪═════╡
│ 2015_01_NO_ARI  ┆ 2015   ┆ 1    ┆ ARI       ┆ … ┆ ARI  ┆ 31         ┆ 19             ┆ 1   │
│ 2015_02_ARI_CHI ┆ 2015   ┆ 2    ┆ CHI       ┆ … ┆ ARI  ┆ 48         ┆ 23             ┆ 1   │
│ 2015_03_SF_ARI  ┆ 2015   ┆ 3    ┆ ARI       ┆ … ┆ ARI  ┆ 47         ┆ 7              ┆ 1   │
│ 2015_04_STL_ARI ┆ 2015   ┆ 4    ┆ ARI       ┆ … ┆ ARI  ┆ 22         ┆ 24             ┆ 0   │
│ 2015_05_ARI_DET ┆ 2015   ┆ 5    ┆ DET       ┆ … ┆ ARI  ┆ 42         ┆ 17             ┆ 1   │
│ 2015_06_ARI_PIT ┆ 2015   ┆ 6    ┆ PIT       ┆ … ┆ ARI  ┆ 13         ┆ 25             ┆ 0   │
│ 2015_07_BAL_ARI ┆ 2015   ┆ 7    ┆ ARI       ┆ … ┆ ARI  ┆ 26         ┆ 18             ┆ 1   │
│ 2015_08_ARI_CLE ┆ 2015   ┆ 8    ┆ CLE       ┆ … ┆ ARI  ┆ 34         ┆ 20             ┆ 1   │
│ 2015_10_ARI_SEA ┆ 2015   ┆ 10   ┆ SEA       ┆ … ┆ ARI  ┆ 39         ┆ 32             ┆ 1   │
│ 2015_11_CIN_ARI ┆ 2015   ┆ 11   ┆ ARI       ┆ … ┆ ARI  ┆ 34         ┆ 31             ┆ 1   │
└─────────────────┴────────┴──────┴───────────┴───┴──────┴────────────┴────────────────┴─────┘

In [11]:
team_games.shape

(5790, 9)

In [12]:
team_games = team_games.with_columns([
    pl.col("win")
    .cum_sum()
    .over(["season", "team"])
    .shift(1)
    .over(["season", "team"])
    .alias("wins_before"),

    pl.col("points_for")
    .cum_sum()
    .over(["season", "team"])
    .shift(1)
    .over(["season", "team"])
    .alias("points_for_before"),

    pl.col("points_against")
    .cum_sum()
    .over(["season", "team"])
    .shift(1)
    .over(["season", "team"])
    .alias("points_against_before"),

    pl.col("win")
    .cum_count()
    .over(["season", "team"])
    .shift(1)
    .over(["season", "team"])
    .alias("games_before"),
])

In [13]:
team_games.head(10)

shape: (10, 13)
┌─────────────┬────────┬──────┬───────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ game_id     ┆ season ┆ week ┆ home_team ┆ … ┆ wins_before ┆ points_for ┆ points_aga ┆ games_befo │
│ ---         ┆ ---    ┆ ---  ┆ ---       ┆   ┆ ---         ┆ _before    ┆ inst_befor ┆ re         │
│ str         ┆ i32    ┆ i32  ┆ str       ┆   ┆ i64         ┆ ---        ┆ e          ┆ ---        │
│             ┆        ┆      ┆           ┆   ┆             ┆ i32        ┆ ---        ┆ u32        │
│             ┆        ┆      ┆           ┆   ┆             ┆            ┆ i32        ┆            │
╞═════════════╪════════╪══════╪═══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2015_01_NO_ ┆ 2015   ┆ 1    ┆ ARI       ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ ARI         ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_02_ARI ┆ 2015   ┆ 2    ┆ CHI       ┆ … ┆ 1           ┆ 31         ┆ 19         ┆ 1          │
│ _CHI        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_03_SF_ ┆ 2015   ┆ 3    ┆ ARI       ┆ … ┆ 2           ┆ 79         ┆ 42         ┆ 2          │
│ ARI         ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_04_STL ┆ 2015   ┆ 4    ┆ ARI       ┆ … ┆ 3           ┆ 126        ┆ 49         ┆ 3          │
│ _ARI        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_05_ARI ┆ 2015   ┆ 5    ┆ DET       ┆ … ┆ 3           ┆ 148        ┆ 73         ┆ 4          │
│ _DET        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_06_ARI ┆ 2015   ┆ 6    ┆ PIT       ┆ … ┆ 4           ┆ 190        ┆ 90         ┆ 5          │
│ _PIT        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_07_BAL ┆ 2015   ┆ 7    ┆ ARI       ┆ … ┆ 4           ┆ 203        ┆ 115        ┆ 6          │
│ _ARI        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_08_ARI ┆ 2015   ┆ 8    ┆ CLE       ┆ … ┆ 5           ┆ 229        ┆ 133        ┆ 7          │
│ _CLE        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_10_ARI ┆ 2015   ┆ 10   ┆ SEA       ┆ … ┆ 6           ┆ 263        ┆ 153        ┆ 8          │
│ _SEA        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
│ 2015_11_CIN ┆ 2015   ┆ 11   ┆ ARI       ┆ … ┆ 7           ┆ 302        ┆ 185        ┆ 9          │
│ _ARI        ┆        ┆      ┆           ┆   ┆             ┆            ┆            ┆            │
└─────────────┴────────┴──────┴───────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [14]:
team_games = team_games.with_columns([
    (
        pl.col("wins_before") /
        pl.col("games_before")
    ).alias("win_pct_before"),

    (
        pl.col("points_for_before") /
        pl.col("games_before")
    ).alias("ppg_before"),

    (
        pl.col("points_against_before") /
        pl.col("games_before")
    ).alias("papg_before"),
])

In [15]:
team_games.select([
    "season",
    "week",
    "team",
    "games_before",
    "win_pct_before",
    "ppg_before",
    "papg_before",
]).head(20)

shape: (20, 7)
┌────────┬──────┬──────┬──────────────┬────────────────┬────────────┬─────────────┐
│ season ┆ week ┆ team ┆ games_before ┆ win_pct_before ┆ ppg_before ┆ papg_before │
│ ---    ┆ ---  ┆ ---  ┆ ---          ┆ ---            ┆ ---        ┆ ---         │
│ i32    ┆ i32  ┆ str  ┆ u32          ┆ f64            ┆ f64        ┆ f64         │
╞════════╪══════╪══════╪══════════════╪════════════════╪════════════╪═════════════╡
│ 2015   ┆ 1    ┆ ARI  ┆ null         ┆ null           ┆ null       ┆ null        │
│ 2015   ┆ 2    ┆ ARI  ┆ 1            ┆ 1.0            ┆ 31.0       ┆ 19.0        │
│ 2015   ┆ 3    ┆ ARI  ┆ 2            ┆ 1.0            ┆ 39.5       ┆ 21.0        │
│ 2015   ┆ 4    ┆ ARI  ┆ 3            ┆ 1.0            ┆ 42.0       ┆ 16.333333   │
│ 2015   ┆ 5    ┆ ARI  ┆ 4            ┆ 0.75           ┆ 37.0       ┆ 18.25       │
│ …      ┆ …    ┆ …    ┆ …            ┆ …              ┆ …          ┆ …           │
│ 2015   ┆ 17   ┆ ARI  ┆ 15           ┆ 0.866667       ┆ 32.2       ┆ 18.466667   │
│ 2015   ┆ 1    ┆ ATL  ┆ null         ┆ null           ┆ null       ┆ null        │
│ 2015   ┆ 2    ┆ ATL  ┆ 1            ┆ 1.0            ┆ 26.0       ┆ 24.0        │
│ 2015   ┆ 3    ┆ ATL  ┆ 2            ┆ 1.0            ┆ 25.0       ┆ 22.0        │
│ 2015   ┆ 4    ┆ ATL  ┆ 3            ┆ 1.0            ┆ 29.666667  ┆ 24.0        │
└────────┴──────┴──────┴──────────────┴────────────────┴────────────┴─────────────┘

In [16]:
team_features = team_games.select([
    "game_id",
    "team",
    "win_pct_before",
    "ppg_before",
    "papg_before",
])

In [17]:
home_features = team_features.rename({
    "team": "home_team",
    "win_pct_before": "home_win_pct",
    "ppg_before": "home_ppg",
    "papg_before": "home_papg",
})

In [18]:
away_features = team_features.rename({
    "team": "away_team",
    "win_pct_before": "away_win_pct",
    "ppg_before": "away_ppg",
    "papg_before": "away_papg",
})

In [21]:
model_data = (
    games
    .with_columns(
        (pl.col("result") > 0)
        .cast(pl.Int8)
        .alias("home_win")
    )
    .join(
        home_features,
        on=["game_id", "home_team"],
        how="left"
    )
    .join(
        away_features,
        on=["game_id", "away_team"],
        how="left"
    )
)

In [23]:
model_data.select([
    "season",
    "week",
    "home_team",
    "away_team",
    "result",
    "home_win",
    "home_win_pct",
    "away_win_pct",
]).head(10)

shape: (10, 8)
┌────────┬──────┬───────────┬───────────┬────────┬──────────┬──────────────┬──────────────┐
│ season ┆ week ┆ home_team ┆ away_team ┆ result ┆ home_win ┆ home_win_pct ┆ away_win_pct │
│ ---    ┆ ---  ┆ ---       ┆ ---       ┆ ---    ┆ ---      ┆ ---          ┆ ---          │
│ i32    ┆ i32  ┆ str       ┆ str       ┆ i32    ┆ i8       ┆ f64          ┆ f64          │
╞════════╪══════╪═══════════╪═══════════╪════════╪══════════╪══════════════╪══════════════╡
│ 2015   ┆ 1    ┆ NE        ┆ PIT       ┆ 7      ┆ 1        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ BUF       ┆ IND       ┆ 13     ┆ 1        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ CHI       ┆ GB        ┆ -8     ┆ 0        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ HOU       ┆ KC        ┆ -7     ┆ 0        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ JAX       ┆ CAR       ┆ -11    ┆ 0        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ NYJ       ┆ CLE       ┆ 21     ┆ 1        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ STL       ┆ SEA       ┆ 3      ┆ 1        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ WAS       ┆ MIA       ┆ -7     ┆ 0        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ ARI       ┆ NO        ┆ 12     ┆ 1        ┆ null         ┆ null         │
│ 2015   ┆ 1    ┆ SD        ┆ DET       ┆ 5      ┆ 1        ┆ null         ┆ null         │
└────────┴──────┴───────────┴───────────┴────────┴──────────┴──────────────┴──────────────┘

In [24]:
model_data = model_data.with_columns([
    (
        pl.col("home_win_pct") -
        pl.col("away_win_pct")
    ).alias("win_pct_diff"),

    (
        pl.col("home_ppg") -
        pl.col("away_ppg")
    ).alias("ppg_diff"),

    (
        pl.col("away_papg") -
        pl.col("home_papg")
    ).alias("defense_diff"),
])

In [25]:
model_data.select([
    "season",
    "week",
    "home_team",
    "away_team",
    "home_win",
    "win_pct_diff",
    "ppg_diff",
    "defense_diff",
]).head(20)

shape: (20, 8)
┌────────┬──────┬───────────┬───────────┬──────────┬──────────────┬──────────┬──────────────┐
│ season ┆ week ┆ home_team ┆ away_team ┆ home_win ┆ win_pct_diff ┆ ppg_diff ┆ defense_diff │
│ ---    ┆ ---  ┆ ---       ┆ ---       ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ i32    ┆ i32  ┆ str       ┆ str       ┆ i8       ┆ f64          ┆ f64      ┆ f64          │
╞════════╪══════╪═══════════╪═══════════╪══════════╪══════════════╪══════════╪══════════════╡
│ 2015   ┆ 1    ┆ NE        ┆ PIT       ┆ 1        ┆ null         ┆ null     ┆ null         │
│ 2015   ┆ 1    ┆ BUF       ┆ IND       ┆ 1        ┆ null         ┆ null     ┆ null         │
│ 2015   ┆ 1    ┆ CHI       ┆ GB        ┆ 0        ┆ null         ┆ null     ┆ null         │
│ 2015   ┆ 1    ┆ HOU       ┆ KC        ┆ 0        ┆ null         ┆ null     ┆ null         │
│ 2015   ┆ 1    ┆ JAX       ┆ CAR       ┆ 0        ┆ null         ┆ null     ┆ null         │
│ …      ┆ …    ┆ …         ┆ …         ┆ …        ┆ …            ┆ …        ┆ …            │
│ 2015   ┆ 1    ┆ SF        ┆ MIN       ┆ 1        ┆ null         ┆ null     ┆ null         │
│ 2015   ┆ 2    ┆ KC        ┆ DEN       ┆ 0        ┆ 0.0          ┆ 8.0      ┆ -7.0         │
│ 2015   ┆ 2    ┆ BUF       ┆ NE        ┆ 0        ┆ 0.0          ┆ -1.0     ┆ 7.0          │
│ 2015   ┆ 2    ┆ CAR       ┆ HOU       ┆ 1        ┆ 1.0          ┆ 0.0      ┆ 18.0         │
│ 2015   ┆ 2    ┆ CHI       ┆ ARI       ┆ 0        ┆ -1.0         ┆ -8.0     ┆ -12.0        │
└────────┴──────┴───────────┴───────────┴──────────┴──────────────┴──────────┴──────────────┘

In [26]:
model_data = model_data.drop_nulls([
    "win_pct_diff",
    "ppg_diff",
    "defense_diff",
])

In [27]:
model_data.shape

(2718, 56)

In [28]:
features = [
    "win_pct_diff",
    "ppg_diff",
    "defense_diff",
]

target = "home_win"

In [29]:
X = model_data.select(features)
y = model_data.select(target).to_series()

In [30]:
print(X.head())
print(y.head())

shape: (5, 3)
┌──────────────┬──────────┬──────────────┐
│ win_pct_diff ┆ ppg_diff ┆ defense_diff │
│ ---          ┆ ---      ┆ ---          │
│ f64          ┆ f64      ┆ f64          │
╞══════════════╪══════════╪══════════════╡
│ 0.0          ┆ 8.0      ┆ -7.0         │
│ 0.0          ┆ -1.0     ┆ 7.0          │
│ 1.0          ┆ 0.0      ┆ 18.0         │
│ -1.0         ┆ -8.0     ┆ -12.0        │
│ 0.0          ┆ 0.0      ┆ 15.0         │
└──────────────┴──────────┴──────────────┘
shape: (10,)
Series: 'home_win' [i8]
[
	0
	0
	1
	0
	1
	1
	1
	0
	0
	1
]

In [31]:
train_data = model_data.filter(
    pl.col("season") <= 2022
)

validation_data = model_data.filter(
    pl.col("season") == 2023
)

test_data = model_data.filter(
    pl.col("season") >= 2024
)

In [32]:
print("Train:", train_data.shape)
print("Validation:", validation_data.shape)
print("Test:", test_data.shape)

Train: (1950, 56)
Validation: (256, 56)
Test: (512, 56)

In [33]:
print(
    train_data
    .select("season")
    .unique()
    .sort("season")
)

print(
    validation_data
    .select("season")
    .unique()
    .sort("season")
)

print(
    test_data
    .select("season")
    .unique()
    .sort("season")
)

shape: (8, 1)
┌────────┐
│ season │
│ ---    │
│ i32    │
╞════════╡
│ 2015   │
│ 2016   │
│ 2017   │
│ 2018   │
│ 2019   │
│ 2020   │
│ 2021   │
│ 2022   │
└────────┘
shape: (1, 1)
┌────────┐
│ season │
│ ---    │
│ i32    │
╞════════╡
│ 2023   │
└────────┘
shape: (2, 1)
┌────────┐
│ season │
│ ---    │
│ i32    │
╞════════╡
│ 2024   │
│ 2025   │
└────────┘

In [34]:
X_train = train_data.select(features).to_numpy()
y_train = train_data.select(target).to_numpy().ravel()

X_val = validation_data.select(features).to_numpy()
y_val = validation_data.select(target).to_numpy().ravel()

X_test = test_data.select(features).to_numpy()
y_test = test_data.select(target).to_numpy().ravel()

In [35]:
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_val:", X_val.shape)
print("y_val:", y_val.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (1950, 3)
y_train: (1950,)
X_val: (256, 3)
y_val: (256,)
X_test: (512, 3)
y_test: (512,)